"""Japanese instrumental seismic-intensity algorithms for Python."""

from . import long_period
from ._version import __version__
from .comparison import compare_intensity_methods
from .duration import (
    amplitude_duration_curve,
    duration_sample_count,
    duration_threshold,
    duration_threshold_at,
    exceedance_duration,
)
from .exceptions import (
    DataFormatError,
    FractionalDurationWarning,
    InsufficientDataError,
    InvalidAccelerationError,
    MissingComponentWarning,
    NonstandardProcessingWarning,
    NonstandardSamplingRateWarning,
    PyShindoError,
    PyShindoWarning,
    UnstableFilterError,
)
from .filters import (
    JMAFilterComponents,
    JMAFilterResult,
    Kunugi2008Parameters,
    Kunugi2012Parameters,
    LowRateGammaPolicy,
    LowRateGammaSet,
    RealtimeFilter,
    apply_jma_filter_fft,
    design_realtime_filter,
    filter_stage_response,
    jma_filter_components,
    jma_filter_response,
    kunugi_2012_analog_amplitude,
    lowrate_gamma_stability_margins,
    lowrate_stability_lower_bounds,
    published_lowrate_gamma_set,
    realtime_filter_response,
)
from .measured import calculate_measured_intensity, measured_intensity
from .models import (
    AmplitudeDurationCurve,
    FilterStage,
    FrequencyResponse,
    IntensityComparisonResult,
    MeasuredIntensityResult,
    MeasuredIntensityTiming,
    RealtimeChunk,
    RealtimeChunkTiming,
    RealtimeIntensityResult,
    RealtimeSample,
    RecursiveFilterDesign,
)
from .realtime import RealtimeIntensityEstimator, calculate_realtime_intensity, realtime_intensity
from .response_spectrum import (
    ResponseSpectrumResult,
    ResponseSpectrumTiming,
    calculate_response_spectrum,
)
from .scale import (
    INTENSITY_INTERVALS,
    IntensityScale,
    classify_intensity,
    classify_intensity_array,
    intensity_from_threshold_acceleration,
    intensity_interval,
    intensity_label,
    intensity_series_from_threshold_acceleration,
    report_intensity,
    report_intensity_array,
    threshold_acceleration_from_intensity,
)
from .signal import (
    ClippingInterval,
    ClippingReport,
    component_peak_acceleration,
    cosine_taper,
    detect_clipping,
    detrend_acceleration,
    peak_ground_acceleration,
    remove_offset,
    resample_acceleration,
    time_axis,
    vector_resultant,
)
from .spectrum_intensity import (
    SpectrumIntensityEstimator,
    SpectrumIntensityResult,
    SpectrumIntensityTiming,
    SpectrumIntensityUpdate,
    calculate_spectrum_intensity,
    default_periods_s,
)
from .strong_motion import (
    apply_strong_motion_displacement_filter,
    apply_strong_motion_velocity_filter,
)
from .synthetic import scale_acceleration_to_intensity, synthetic_three_component_motion
from .units import STANDARD_GRAVITY_MPS2, AccelerationUnit, convert_acceleration, to_gal
from .validation import SamplingDiagnostics, sampling_diagnostics
from .velocity import (
    component_peak_displacement,
    component_peak_velocity,
    integrate_to_displacement,
    integrate_to_velocity,
    peak_ground_displacement,
    peak_ground_velocity,
)

__all__ = [
    "AccelerationUnit",
    "AmplitudeDurationCurve",
    "ClippingInterval",
    "ClippingReport",
    "DataFormatError",
    "FilterStage",
    "FractionalDurationWarning",
    "FrequencyResponse",
    "INTENSITY_INTERVALS",
    "InsufficientDataError",
    "IntensityComparisonResult",
    "IntensityScale",
    "InvalidAccelerationError",
    "JMAFilterComponents",
    "JMAFilterResult",
    "Kunugi2008Parameters",
    "Kunugi2012Parameters",
    "LowRateGammaPolicy",
    "LowRateGammaSet",
    "MeasuredIntensityResult",
    "MeasuredIntensityTiming",
    "MissingComponentWarning",
    "NonstandardProcessingWarning",
    "NonstandardSamplingRateWarning",
    "PyShindoError",
    "PyShindoWarning",
    "RealtimeChunk",
    "RealtimeChunkTiming",
    "RealtimeFilter",
    "RealtimeIntensityEstimator",
    "RealtimeIntensityResult",
    "RealtimeSample",
    "RecursiveFilterDesign",
    "ResponseSpectrumResult",
    "ResponseSpectrumTiming",
    "STANDARD_GRAVITY_MPS2",
    "SamplingDiagnostics",
    "SpectrumIntensityEstimator",
    "SpectrumIntensityResult",
    "SpectrumIntensityTiming",
    "SpectrumIntensityUpdate",
    "UnstableFilterError",
    "__version__",
    "amplitude_duration_curve",
    "apply_jma_filter_fft",
    "apply_strong_motion_displacement_filter",
    "apply_strong_motion_velocity_filter",
    "calculate_measured_intensity",
    "calculate_realtime_intensity",
    "calculate_response_spectrum",
    "calculate_spectrum_intensity",
    "classify_intensity",
    "classify_intensity_array",
    "compare_intensity_methods",
    "component_peak_acceleration",
    "component_peak_displacement",
    "component_peak_velocity",
    "convert_acceleration",
    "cosine_taper",
    "default_periods_s",
    "design_realtime_filter",
    "detect_clipping",
    "detrend_acceleration",
    "duration_sample_count",
    "duration_threshold",
    "duration_threshold_at",
    "exceedance_duration",
    "filter_stage_response",
    "integrate_to_displacement",
    "integrate_to_velocity",
    "intensity_from_threshold_acceleration",
    "intensity_interval",
    "intensity_label",
    "intensity_series_from_threshold_acceleration",
    "jma_filter_components",
    "jma_filter_response",
    "kunugi_2012_analog_amplitude",
    "long_period",
    "lowrate_gamma_stability_margins",
    "lowrate_stability_lower_bounds",
    "measured_intensity",
    "peak_ground_acceleration",
    "peak_ground_displacement",
    "peak_ground_velocity",
    "published_lowrate_gamma_set",
    "realtime_filter_response",
    "realtime_intensity",
    "remove_offset",
    "report_intensity",
    "report_intensity_array",
    "resample_acceleration",
    "sampling_diagnostics",
    "scale_acceleration_to_intensity",
    "synthetic_three_component_motion",
    "threshold_acceleration_from_intensity",
    "time_axis",
    "to_gal",
    "vector_resultant",
]
