"""Japanese instrumental seismic-intensity algorithms for Python."""

from ._version import __version__
from .comparison import compare_intensity_methods
from .duration import (
    amplitude_duration_curve,
    duration_sample_count,
    duration_threshold,
    duration_threshold_at,
    exceedance_duration,
)
from .filters import (
    JMAFilterComponents,
    Kunugi2008Parameters,
    Kunugi2012Parameters,
    LowRateGammaPolicy,
    LowRateGammaSet,
    RealtimeFilter,
    apply_jma_filter_fft,
    design_realtime_filter,
    filter_stage_response,
    jma_filter_components,
    jma_filter_response,
    kunugi_2012_analog_amplitude,
    lowrate_gamma_stability_margins,
    lowrate_stability_lower_bounds,
    published_lowrate_gamma_set,
    realtime_filter_response,
)
from .measured import calculate_measured_intensity, measured_intensity
from .models import (
    AmplitudeDurationCurve,
    FilterStage,
    FrequencyResponse,
    IntensityComparisonResult,
    MeasuredIntensityResult,
    RealtimeChunk,
    RealtimeIntensityResult,
    RealtimeSample,
    RecursiveFilterDesign,
)
from .realtime import RealtimeIntensityEstimator, calculate_realtime_intensity, realtime_intensity
from .scale import (
    INTENSITY_INTERVALS,
    IntensityScale,
    acceleration_from_intensity,
    classify_intensity,
    intensity_from_acceleration,
    intensity_label,
    report_intensity,
)
from .signal import (
    component_peak_acceleration,
    cosine_taper,
    detrend_acceleration,
    peak_ground_acceleration,
    remove_offset,
    resample_acceleration,
    time_axis,
    vector_resultant,
)
from .synthetic import scale_acceleration_to_intensity, synthetic_three_component_motion
from .units import STANDARD_GRAVITY_MPS2, AccelerationUnit, convert_acceleration, to_gal
from .validation import SamplingDiagnostics, sampling_diagnostics

__all__ = [
    "INTENSITY_INTERVALS",
    "JMAFilterComponents",
    "STANDARD_GRAVITY_MPS2",
    "AccelerationUnit",
    "AmplitudeDurationCurve",
    "__version__",
    "FilterStage",
    "FrequencyResponse",
    "IntensityComparisonResult",
    "IntensityScale",
    "Kunugi2008Parameters",
    "Kunugi2012Parameters",
    "LowRateGammaPolicy",
    "LowRateGammaSet",
    "MeasuredIntensityResult",
    "RealtimeChunk",
    "RealtimeFilter",
    "RealtimeIntensityEstimator",
    "RealtimeIntensityResult",
    "RealtimeSample",
    "RecursiveFilterDesign",
    "SamplingDiagnostics",
    "acceleration_from_intensity",
    "amplitude_duration_curve",
    "apply_jma_filter_fft",
    "calculate_measured_intensity",
    "calculate_realtime_intensity",
    "classify_intensity",
    "compare_intensity_methods",
    "component_peak_acceleration",
    "convert_acceleration",
    "cosine_taper",
    "design_realtime_filter",
    "detrend_acceleration",
    "duration_sample_count",
    "duration_threshold",
    "duration_threshold_at",
    "exceedance_duration",
    "filter_stage_response",
    "intensity_from_acceleration",
    "intensity_label",
    "jma_filter_components",
    "jma_filter_response",
    "kunugi_2012_analog_amplitude",
    "lowrate_gamma_stability_margins",
    "lowrate_stability_lower_bounds",
    "measured_intensity",
    "peak_ground_acceleration",
    "published_lowrate_gamma_set",
    "realtime_filter_response",
    "realtime_intensity",
    "remove_offset",
    "report_intensity",
    "resample_acceleration",
    "sampling_diagnostics",
    "scale_acceleration_to_intensity",
    "synthetic_three_component_motion",
    "time_axis",
    "to_gal",
    "vector_resultant",
]
